version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: MyDB
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - 3TierApp-Network  # Use the existing network

  backend:
    build:
      context: ./student-backendSpringboot/student
      dockerfile: Dockerfile
    container_name: student-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/MyDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Test@123
      CORS_ALLOWED_ORIGINS: http://student-frontend:3000
    ports:
      - "8081:8081"
    depends_on:
      - database
    networks:
      - 3TierApp-Network  # Use the existing network

  frontend:
    build:
      context: ./student-frontendReact/student
      dockerfile: Dockerfile
    container_name: student-frontend
    environment:
      REACT_APP_BACKEND_URL: http://student-backend:8081
    ports:
      - "3000:3000"
    networks:
      - 3TierApp-Network  # Use the existing network

volumes:
  db_data:

networks:
  3TierApp-Network:
    external: true  # Indicate that this network already exists

